Feature/10 liquibase integration
rohitnandi12/learn-by-coding-community pull request #22
Opened 2024-11-18 13:14 UTC by damini1994

2024-11-21 08:02 UTC, rohitnandi12 requested changes
Add this in properties file

spring.jpa.hibernate.ddl-auto: validate

run the application and update the Entities if it is breaking

2024-11-21 08:02 UTC, rohitnandi12 commented on book-my-show/backend/java/bms-monolith/src/main/resources/db/changelog/v1.0/create-tables.xml
> +        <createTable tableName="event">
Lets follow table names to be plural like "events"

2024-11-21 08:02 UTC, rohitnandi12 commented on book-my-show/backend/java/bms-monolith/src/main/resources/db/changelog/v1.0/create-tables.xml
> +                <constraints primaryKey="true" nullable="false"/>
is nullable=false required? Primary Key is going to be unique and not-null by default

2024-11-21 08:02 UTC, rohitnandi12 commented on book-my-show/backend/java/bms-monolith/src/main/resources/db/changelog/v1.0/create-tables.xml
> +            <column name="status" type="VARCHAR(20)" />
can we add a check constraint here?

2024-11-21 08:02 UTC, rohitnandi12 commented on book-my-show/backend/java/bms-monolith/src/main/resources/db/changelog/v1.0/create-tables.xml
> +            <column name="registration_date" type="VARCHAR(100)" />
type=timestamp

2024-11-21 08:02 UTC, rohitnandi12 commented on book-my-show/backend/java/bms-monolith/src/main/resources/db/changelog/v1.0/create-tables.xml
> +            <column name="name" type="VARCHAR(255)" />
VARCHAR(20)

2024-11-21 08:02 UTC, rohitnandi12 commented on book-my-show/backend/java/bms-monolith/src/main/resources/db/changelog/v1.0/create-tables.xml
> +            </column>
same as above

2024-11-21 08:02 UTC, rohitnandi12 commented on book-my-show/backend/java/bms-monolith/src/main/resources/db/changelog/v1.0/create-tables.xml
> +            <column name="operational_status" type="VARCHAR(20)" />
check constraint

2024-11-21 08:02 UTC, rohitnandi12 commented on book-my-show/backend/java/bms-monolith/src/main/resources/db/changelog/v1.0/create-tables.xml
> +            </column>
"event_shows"
same as above

2024-11-21 08:02 UTC, rohitnandi12 commented on book-my-show/backend/java/bms-monolith/src/main/resources/db/changelog/v1.0/create-tables.xml
> +            </column>
event_types

2024-11-21 08:02 UTC, rohitnandi12 commented on book-my-show/backend/java/bms-monolith/src/main/resources/db/changelog/v1.0/create-tables.xml
> +        <createTable tableName="seat">
seats

2024-11-21 08:02 UTC, rohitnandi12 commented on book-my-show/backend/java/bms-monolith/src/main/resources/db/changelog/v1.0/create-tables.xml
> +            <column name="operational_status" type="VARCHAR(20)" />
check constraint

2024-11-21 08:02 UTC, rohitnandi12 commented on book-my-show/backend/java/bms-monolith/src/main/resources/db/changelog/v1.0/create-tables.xml
> +        <createTable tableName="seat_type">
seat_types

2024-11-21 08:02 UTC, rohitnandi12 commented on book-my-show/backend/java/bms-monolith/src/main/resources/db/changelog/v1.0/create-tables.xml
> +            <column name="show_id" type="CHAR(36)" />
nullable = false

2024-11-21 08:02 UTC, rohitnandi12 commented on book-my-show/backend/java/bms-monolith/src/main/resources/db/changelog/v1.0/create-tables.xml
> +            <column name="seat_type_id" type="CHAR(36)" />
nullable=false

2024-11-21 08:02 UTC, rohitnandi12 commented on book-my-show/backend/java/bms-monolith/src/main/resources/db/changelog/v1.0/create-tables.xml
> +            </column>
seat_type_in_shows

2024-11-21 08:02 UTC, rohitnandi12 commented on book-my-show/backend/java/bms-monolith/src/main/resources/db/changelog/v1.0/create-tables.xml
> +            <column name="genre" type="VARCHAR(15)">
change name to label

2024-11-21 08:02 UTC, rohitnandi12 commented on book-my-show/backend/java/bms-monolith/src/main/resources/db/changelog/v1.0/create-tables.xml
> +            </column>
same as above

2024-11-21 08:02 UTC, rohitnandi12 commented on book-my-show/backend/java/bms-monolith/src/main/resources/db/changelog/v1.0/add-constraints.xml
> +    </changeSet>
we can directly add the not_null constraint while creating table

2024-11-21 08:02 UTC, rohitnandi12 commented on book-my-show/backend/java/bms-monolith/src/main/resources/db/changelog/v1.0/add-constraints.xml
> +    </changeSet>
add constraint while creating table

2024-11-24 05:07 UTC, damini1994 commented on book-my-show/backend/java/bms-monolith/src/main/resources/db/changelog/v1.0/create-tables.xml
> +            <column name="status" type="VARCHAR(20)" />
Yes, we can
Added check constraint

2024-11-24 16:02 UTC, rohitnandi12 requested changes

2024-11-24 16:02 UTC, rohitnandi12 commented on book-my-show/backend/java/bms-monolith/src/main/resources/db/changelog/v1.0/create-tables.xml
> +        <createTable tableName="venue">
"venues"

2024-11-24 16:02 UTC, rohitnandi12 commented on book-my-show/backend/java/bms-monolith/src/main/java/org/lbcc/bms/bms_monolith/common/entity/Venue.java
>  public class Venue extends BaseAuditingEntity {
@ Table(venues)

2024-11-24 16:02 UTC, rohitnandi12 commented on book-my-show/backend/java/bms-monolith/src/main/java/org/lbcc/bms/bms_monolith/common/entity/Vendor.java
> +    @NotNull(message = "Registration date cannot be null.")
@NotNull or @NotBlank are spring validations and not hibernate validations. They are valid only in DTO/Reques objects.

Remove all Spring Validations at Entity level.

2024-11-25 18:24 UTC, rohitnandi12 approved these changes

2024-11-25 18:24 UTC, merged